#!/bin/bash

# Expects $1 file of the form:
#
# [config_name] [options]
#
# For example, the line in $1:
#
#   default --full-saturate-quant
#
# generates starexec_run_default with run command ./cvc4 --full-saturate $1.

NUMCONFIGS=$(wc -l $1 | sed 's/ .*//')
echo "Generating starexec configurations for ${NUMCONFIGS} configurations..."

for ((i=1; i<=NUMCONFIGS; i++)); do
    echo "$i:"
    sed "${i}q;d" $1 > temp.txt
    RESULT=$(cat temp.txt | sed 's/,.*//')
    echo "result is $RESULT"
    echo "#!/bin/bash" > starexec_run_$RESULT
    echo "./cvc4" > temp2.txt
    cat temp.txt | sed 's/.*,/ /' >> temp2.txt
    echo " \$1" >> temp2.txt
    tr -d '\n' < temp2.txt >> starexec_run_$RESULT
    echo >> starexec_run_$RESULT
  done
  
rm -f temp.txt
rm -f temp2.txt
