#!/bin/bash

# manually change to relevant configuration subdirectory
BIN_DIR=starexec-deep-restart

if [ X$1 = X'-p' ]; then
  NAME=$2-cvc5
  shift
  shift
else
  NAME=cvc5
fi

echo "*** Make starexec package from executable $NAME"
$NAME --show-config | grep scm

# Run : mk_starexec [TEXT] 
# Run from directory containing cvc5 binary and subdirectory starexec/ containing the starexec space, i.e. subdirectory bin/ with configuration files.
# Generates file cvc5-[TEXT].tgz that can be uploaded to starexec.
strip ~/bin/$NAME
rm -rf starexec
cp -r $BIN_DIR starexec
cp ~/bin/$NAME ~/bin/cvc5-$1
cd starexec
echo "*** Using configure directory $BIN_DIR:"
cd bin
ls
cd ..
cp ~/bin/$NAME ./bin/cvc5
tar -czf ../cvc5-$1.tgz .
rm ./bin/cvc5
cd ..
echo "*** Finished."
rm -rf starexec
